.. ; -*- mode:rst; -*-

===================================
Reservoir of unbaked ideas for XCVB
===================================

This directory contains files with unbaked ideas.
These files must go, but it's not always clear yet where they should go:
somewhere inside XCVB to offer a new feature,
out in the wild world to live a life of adventure, or
directly into the dust bin of computer history.

.. contents::
..
    1  memoization.lisp
    2  operations.lisp
    3  parse-formals.lisp
    4  misc.lisp


memoization.lisp
----------------

A simple library for memoizing function.

This library is not actually used in XCVB.
I originally intended to use it for interning elements
of some classes where all slots are read-only.

TODO: move to some other CL library, e.g. fare-utils, or its own.


operations.lisp
---------------

Vague ideas about how to possibly organize XCVB
around higher-level "operations" that would be abstract functions
describing how to build the graph, instead of "computations"
that are actual graph nodes.
This was inspired by the desire to have operations as in
defsystem, ASDF, Robbins' BUILD, or Pitman's "Large Systems".

In practice, this seems to have been completely superseded by
the "dependencies" language as specified in ``dependencies-interpreter.lisp``
and its backends in ``static-backends.lisp``.


parse-formals.lisp
------------------

Attempt to parse CL formals to build arity checkers.
Only support formals for LAMBDA and DEFUN, not for DEFMETHOD.


misc.lisp
---------

Assorted functions.

Currently, only one function written to support projects that would span
multiple CL implementations at once. Not quite a priority.
