#+xcvb (module (:depends-on ("/asdf" "/xcvb/driver" "specials")))

(in-package :xcvb-hello)

(asdf:find-system :xcvb)

(defparameter *xcvb-path*
  (asdf:ensure-directory-pathname (asdf:system-source-directory :xcvb)))

(defparameter *hello-version-path*
  (asdf:system-relative-pathname :xcvb "examples/hello/version.lisp"))

(with-open-file (s *hello-version-path* :direction :output
                   :if-exists :rename-and-delete :if-does-not-exist :create)
  (format s ";;; automatically generated by /xcvb/hello/generate-version~%~
             (in-package :xcvb-hello)~%(setf *version* ~S)~%"
          (first
           (run-program/read-output-lines
            (format nil "cd ~A ; git describe --tags" *xcvb-path*)))))
