PREFIX ?= /usr/local
LISP ?= clisp
INSTALL_BIN ?= ${PREFIX}/bin
LISP_SOURCE ?= ${PREFIX}/share/common-lisp/source

export XCVB_PATH := $(shell pwd)

install:
        mkdir -p ${INSTALL_BIN}
	./dependencies/cl-launch/cl-launch.sh \
		-I ${LISP_SOURCE}/cl-launch \
		-o ${INSTALL_BIN}/cl-launch \
		-B install
        export PATH=${INSTALL_BIN}:$PATH ; \
	${MAKE} -C xcvb -j install \
		PREFIX=${PREFIX} LISP=${LISP}
